import type { LucideIcon } from 'lucide-react'
import {
  Bell,
  BellRing,
  Box,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Grip,
  Handshake,
  Hash,
  Info,
  Layers,
  LayoutDashboard,
  ListFilter,
  Loader2,
  MessageSquare,
  MousePointerClick,
  Navigation,
  PanelLeft,
  PanelRight,
  Search,
  Settings,
  Sparkles,
  Tag,
  TextCursorInput,
  ToggleLeft,
  Type,
  X,
} from 'lucide-react'

export type IconComponent = LucideIcon

/**
 * Registry: normalized name (kebab-case) -> Lucide component.
 * Used first when resolving by name; Tabler can be registered as fallback.
 */
export const LUCIDE_REGISTRY: Record<string, IconComponent> = {
  'bell': Bell,
  'bell-ring': BellRing,
  'box': Box,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  'grip': Grip,
  'handshake': Handshake,
  'hash': Hash,
  'info': Info,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'list-filter': ListFilter,
  'loader': Loader2,
  'loader-2': Loader2,
  'message-square': MessageSquare,
  'mouse-pointer-click': MousePointerClick,
  'navigation': Navigation,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'search': Search,
  'settings': Settings,
  'sparkles': Sparkles,
  'tag': Tag,
  'text-cursor-input': TextCursorInput,
  'toggle-left': ToggleLeft,
  'type': Type,
  'x': X,
}
