import type { LucideIcon } from 'lucide-react'
import {
  Bell,
  BellRing,
  Box,
  Calendar,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ExternalLink,
  Grip,
  GripVertical,
  Handshake,
  Hash,
  Info,
  Layers,
  LayoutDashboard,
  ListFilter,
  Loader2,
  MessageSquare,
  MousePointerClick,
  Minus,
  Navigation,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  Search,
  Settings,
  Sparkles,
  MoreVertical,
  Pencil,
  Trash2,
  Tag,
  TextCursorInput,
  ToggleLeft,
  Type,
  User,
  X,
} from 'lucide-react'

export type IconComponent = LucideIcon

/**
 * Registry: normalized name (kebab-case) -> Lucide component.
 * Used first when resolving by name; Tabler can be registered as fallback.
 */
export const LUCIDE_REGISTRY: Record<string, IconComponent> = {
  'bell': Bell,
  'notifications': Bell,
  'bell-ring': BellRing,
  'box': Box,
  'calendar': Calendar,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-down': ArrowUpDown,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  'question': CircleHelp,
  'grip': Grip,
  'grip-vertical': GripVertical,
  'change-product': Grip,
  'handshake': Handshake,
  'hash': Hash,
  'info': Info,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'list-filter': ListFilter,
  'loader': Loader2,
  'loader-2': Loader2,
  'message-square': MessageSquare,
  'mouse-pointer-click': MousePointerClick,
  'navigation': Navigation,
  'panel-left': PanelLeft,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'panel-right': PanelRight,
  'search': Search,
  'settings': Settings,
  'more-vertical': MoreVertical,
  'edit': Pencil,
  'delete': Trash2,
  'sparkles': Sparkles,
  'sparks': Sparkles,
  'tag': Tag,
  'text-cursor-input': TextCursorInput,
  'toggle-left': ToggleLeft,
  'type': Type,
  'x': X,
  'minus': Minus,
  'external-link': ExternalLink,
  'redirect': ExternalLink,
  'user': User,
}
